export const SET_IS_LOADING_FILE = "SET_IS_LOADING_FILE";
export const SET_IS_SAVING_FILE = "SET_IS_SAVING_FILE";
export const LOAD_FILE_SUCCESS = "LOAD_FILE_SUCCESS";
export const LOAD_FILE_FAILURE = "LOAD_FILE_FAILURE";
export const SAVE_FILE_SUCCESS = "SAVE_FILE_SUCCESS";
export const SAVE_FILE_FAILURE = "SAVE_FILE_FAILURE";
export const CLOSE_FILE = "CLOSE_FILE";
